const INITIAL_STATE = {
  application: {
    data: [
      {
        active_lease: 'false',
        apartment_building_id: '0011I0000187qgxQAA',
        apartment_building_name: 'The Social Blue **',
        app_id: '0011I00001HdXV8QAN',
        app_type: null,
        cancellation_reason: null,
        coverage_amount_requested_months: null,
        coverageamountrequested1: null,
        createdAt: '2022-04-22T06:17:16.169Z',
        damages_premium: null,
        decline_reason_1: 'Assets/Income',
        estimated_app_decline_rate: null,
        gross_annual_rent: '6948',
        gross_monthly_rent: '579',
        id: 2,
        insurer: null,
        issue_date: null,
        landlord_id: '0011I00000pd25LQAQ',
        lanlord_account_name: 'Campus Advantage',
        ldr_coverage: null,
        leap_total_inventory: '0.98',
        lease_end_date: null,
        lease_start_date: null,
        months_remaining: null,
        name: 'Chapple - 2707 S Rutherford Blvd',
        rider_id: 'LEAP-0044061',
        sf_createdDate: '2020-07-24T12:27:22.000+0000',
        stage: '06 - Policy Declined',
        tenant_1_contact_id: '0031I000019udW5QAI',
        tenant_1_fee_input: null,
        tenant_1_id: '0031I000019udW5QAI',
        tenant_1_name: 'Jayla Chapple',
        tenant_1_portion_fee: '0',
        total_active_leap_units: '5',
        total_coverage_amount: '0',
        total_number_of_tenants: '1',
        total_units: '512',
        updatedAt: '2022-04-22T06:17:16.169Z',
      },
      {
        active_lease: 'false',
        apartment_building_id: '0011I00000wOoSbQAK',
        apartment_building_name: 'The Rowan',
        app_id: '0011I00001ZeqWyQAJ',
        app_type: 'Rent Guaranty',
        cancellation_reason: null,
        coverage_amount_requested_months: '7',
        coverageamountrequested1: null,
        createdAt: '2022-04-22T06:17:16.169Z',
        damages_premium: '0',
        decline_reason_1: null,
        estimated_app_decline_rate: null,
        gross_annual_rent: '8520',
        gross_monthly_rent: '710',
        id: 191,
        insurer: 'Accelerant',
        issue_date: null,
        landlord_id: '0011I00000pd25LQAQ',
        lanlord_account_name: 'Campus Advantage',
        ldr_coverage: null,
        leap_total_inventory: '6.29',
        lease_end_date: null,
        lease_start_date: null,
        months_remaining: null,
        name: 'Robinson-1051 Southern Drive',
        rider_id: 'LEAP-0199814',
        sf_createdDate: '2021-07-30T19:11:43.000+00,00',
        stage: 'Duplicate Application',
        tenant_1_contact_id: '0031I00001R2GzzQAF',
        tenant_1_fee_input: null,
        tenant_1_id: '0031I00001R2GzzQAF',
        tenant_1_name: 'Mercedes Robinson',
        tenant_1_portion_fee: '0',
        total_active_leap_units: '63',
        total_coverage_amount: null,
        total_number_of_tenants: '1',
        total_units: '1002',
        updatedAt: '2022-04-22T06:17:16.169Z',
      }
    ]
  },
  building: {
    data: [
      {
        billingCity: 'Ames',
        billingState: 'IA',
        billingStreet: '1206 S. 4th St Suite 101',
        building_approval_rate: '16.67',
        building_approved_to_issue_rate: null,
        building_id: '0011I000013EyjKQAS',
        building_type: null,
        cancellation_percentage: '25',
        createdAt: '2022-04-13T06:14:30.533Z',
        decline_percentage: '62.5',
        email_address: 'leasing@stadiumviewames.com',
        estimated_applicant_decline_rate: null,
        id: 119,
        landlord_id: '0011I00000pd25LQAQ',
        landlord_name: 'Campus Advantage',
        last_application_date: '2021-11-07',
        leap_of_total_inventory: null,
        name: 'Stadium View Ames',
        phone: '(515) 296-4787',
        primary_contact: 'leasing@stadiumviewames.com',
        property_owner: null,
        sf_createdDate: '2019-08-29T21:20:00.000+0000',
        student_housing: 'true',
        total_of_active_leap_units: null,
        total_of_applications: '8',
        total_of_approved_app: '1',
        total_of_cancelled_applications: '2',
        total_of_decisioned_app: '6',
        total_of_declined_applications: '5',
        total_of_issued_policies: null,
        total_of_units: '518',
        updatedAt: '2022-04-13T06:14:30.533Z',
      },
      {
        billingCity: 'San Antonio',
        billingState: 'TX',
        billingStreet: '7114 UTSA Boulevard',
        building_approval_rate: '116.67',
        building_approved_to_issue_rate: '7.14',
        building_id: '0011I00000xlpbJQAQ',
        building_type: null,
        cancellation_percentage: '92.86',
        createdAt: '2022-04-13T06:14:30.533Z',
        decline_percentage: '0',
        email_address: 'migonzalez@pradostudentliving.com',
        estimated_applicant_decline_rate: null,
        id: 230,
        landlord_id: '0011I00000pd25LQAQ',
        landlord_name: 'Campus Advantage',
        last_application_date: '2021-05-12',
        leap_of_total_inventory: null,
        name: 'Prado Student Living',
        phone: '(210) 853-0001',
        primary_contact: 'leasing@pradostudent,living.com',
        property_owner: null,
        sf_createdDate: '2019-07-01T16:49:57.000+0000',
        student_housing: 'true',
        total_of_active_leap_units: null,
        total_of_applications: '14',
        total_of_approved_app: '14',
        total_of_cancelled_applications: '13',
        total_of_decisioned_app: '12',
        total_of_declined_applications: null,
        total_of_issued_policies: '1',
        total_of_units: '468',
        updatedAt: '2022-04-13T06:14:30.533Z',
      }
    ]
  },
  claim: {
    data: [
      {
        account_name: 'Seisay - 316 Columbia Dr., 809-D',
        apartment_building_address: '316 Columbia Drive, Carrollton, GA, 30117',
        apartment_building_id: '0011I00000pmIYiQAM',
        app_type: 'Rent Guaranty',
        bond_issue_date: '2019-07-22',
        claim_status: 'Opened',
        createdAt: '2022-04-22T14:46:39.256Z',
        id: 1,
        landlord_id: '0011I00000pd25LQAQ',
        landlord_name: 'Campus Advantage',
        lease_end_date: '2020-07-20',
        lease_start_date: '2019-08-08',
        monthly_rent: '455',
        rider_active_lease: 'false',
        rider_coverage_amount_requested_months: null,
        rider_damage_coverage_amount: '0',
        rider_gross_annual_rent: '5460',
        rider_id: 'LEAP-0007084',
        rider_insurable_value: null,
        rider_ldr_coverage_c: null,
        rider_months_remaining: '0',
        rider_total_coverage_amount: '3185',
        rider_total_number_of_tenants: '1',
        rider_total_rent: '5195.81',
        tenant1_lease: 'Kadija Seisay',
        tenant2_lease: null,
        tenant3_lease: null,
        tenant4_lease: null,
        total_indemnity_payments: '1365',
        updatedAt: '2022-04-22T14:46:39.256Z',
      },
      {
        account_name: 'GUO - 4220 24th St, #36D',
        apartment_building_address: '23-10 Queens Plaza South, Long Island City, NY, 11101',
        apartment_building_id: '0011I00000tEcgXQAS',
        app_type: 'Rent Guaranty',
        bond_issue_date: '2019-09-10',
        claim_status: 'Closed',
        createdAt: '2022-04-22T14:46:39.256Z',
        id: 2,
        landlord_id: '0011I00000pmIatQAE',
        landlord_name: 'Stonehenge',
        lease_end_date: '2020-09-30',
        lease_start_date: '2019-09-26',
        monthly_rent: '5667.69',
        rider_active_lease: 'false',
        rider_coverage_amount_requested_months: null,
        rider_damage_coverage_amount: '0',
        rider_gross_annual_rent: '68012.28',
        rider_id: 'LEAP-0011832',
        rider_insurable_value: null,
        rider_ldr_coverage_c: null,
        rider_months_remaining: '0',
        rider_total_coverage_amount: '68012.28',
        rider_total_number_of_tenants: '1',
        rider_total_rent: '68926.42',
        tenant1_lease: 'Jinting Guo (Apartment 36D)',
        tenant2_lease: null,
        tenant3_lease: null,
        tenant4_lease: null,
        total_indemnity_payments: '6084.77',
        updatedAt: '2022-04-22T14:46:39.256Z',
      }
    ]
  }
};

export default INITIAL_STATE;
