const userActionTypes = {
  LOG_IN_START: 'LOG_IN_START',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_IN_FAILURE: 'LOG_IN_FAILURE',
  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  LOG_OUT: 'LOG_OUT',
  EMAIL_VERIFY: 'EMAIL_VERIFY',
  EMAIL_VERIFY_SUCCESS: 'EMAIL_VERIFY_SUCCESS',
  EMAIL_VERIFY_FAILURE: 'EMAIL_VERIFY_FAILURE'
};

export default userActionTypes;
