const userActionTypes = {
  GET_LL: 'GET_LL',
  SET_LL: 'SET_LL',
  GET_VP: 'GET_VP',
  GET_RM: 'GET_RM',
  SET_VP: 'SET_VP',
  SET_RM: 'SET_RM',
  SET_ERR: 'GET_ERR',
  GET_PM: 'GET_PM',
  SET_PM: 'SET_PM',
  GET_USER_BUILDING: 'GET_USER_BUILDING',
  SET_USER_BUILDING: 'SET_USER_BUILDING',
  GET_USER_APP: 'GET_USER_APP',
  GET_USER_CLAIM: 'GET_USER_CLAIM',
  SET_USER_APP: 'SET_USER_APP',
  SET_USER_CLAIM: 'SET_USER_CLAIM',
  GET_USER_POLICY: 'GET_USER_POLICY',
  SET_USER_POLICY: 'SET_USER_POLICY'
};

export default userActionTypes;
